# Generated by Django 3.2.10 on 2022-07-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('deposit', models.IntegerField(default=None)),
                ('monthlyRent', models.IntegerField(default=None)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('moldScore', models.FloatField(default=None)),
                ('bugScore', models.FloatField(default=None)),
                ('smellScore', models.FloatField(default=None)),
                ('cleanAvg', models.FloatField(default=None)),
                ('internalNoiseScore', models.FloatField(default=None)),
                ('externalNoiseScore', models.FloatField(default=None)),
                ('floorNoiseScore', models.FloatField(default=None)),
                ('noiseAvg', models.FloatField(default=None)),
                ('parkingScore', models.FloatField(default=None)),
                ('managementScore', models.FloatField(default=None)),
                ('constructionScore', models.FloatField(default=None)),
                ('elevator', models.BooleanField(default=False)),
                ('locationsAvg', models.FloatField(default=None)),
                ('femaleOnly', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('courierBox', models.BooleanField(default=False)),
                ('safeAvg', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True, default='', null=True)),
                ('recommend', models.PositiveIntegerField(default=0)),
                ('userId', models.IntegerField(blank=True, default=None, null=True)),
                ('buildingId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.building')),
            ],
        ),
    ]
