# Generated by Django 3.2 on 2022-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtest',
            name='recommend',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewtest',
            name='contents',
            field=models.TextField(default='', null=True),
        ),
    ]
