# Generated by Django 3.2.10 on 2022-07-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtest',
            name='userId',
            field=models.IntegerField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
