# Generated by Django 3.2 on 2022-07-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationevaluation',
            name='buildingId',
        ),
        migrations.RemoveField(
            model_name='noiseevaluation',
            name='buildingId',
        ),
        migrations.RemoveField(
            model_name='safetyevaluation',
            name='buildingId',
        ),
        migrations.RemoveField(
            model_name='reviewtest',
            name='userId',
        ),
        migrations.DeleteModel(
            name='CleanlinessEvaluation',
        ),
        migrations.DeleteModel(
            name='LocationEvaluation',
        ),
        migrations.DeleteModel(
            name='NoiseEvaluation',
        ),
        migrations.DeleteModel(
            name='SafetyEvaluation',
        ),
    ]
