<<<<<<< HEAD
# Generated by Django 3.2.10 on 2022-07-14 09:34
=======
# Generated by Django 3.2.10 on 2022-07-14 09:35
>>>>>>> 5e5e79000671592974f0bdb4daf8df7bd5ac31f9

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building')),
=======
                ('buildingId', models.ForeignKey(db_column='buildingId', on_delete=django.db.models.deletion.CASCADE, to='review.building')),
>>>>>>> 5e5e79000671592974f0bdb4daf8df7bd5ac31f9
            ],
        ),
        migrations.CreateModel(
            name='NoiseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building')),
=======
                ('buildingId', models.ForeignKey(db_column='buildingId', on_delete=django.db.models.deletion.CASCADE, to='review.building')),
>>>>>>> 5e5e79000671592974f0bdb4daf8df7bd5ac31f9
            ],
        ),
        migrations.CreateModel(
            name='LocationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building')),
=======
                ('buildingId', models.ForeignKey(db_column='buildingId', on_delete=django.db.models.deletion.CASCADE, to='review.building')),
>>>>>>> 5e5e79000671592974f0bdb4daf8df7bd5ac31f9
            ],
        ),
        migrations.CreateModel(
            name='CleanlinessEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building')),
=======
                ('buildingId', models.ForeignKey(db_column='buildingId', on_delete=django.db.models.deletion.CASCADE, to='review.building')),
>>>>>>> 5e5e79000671592974f0bdb4daf8df7bd5ac31f9
            ],
        ),
    ]
