# Generated by Django 3.2.10 on 2022-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewtest_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtest',
            name='userId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
