# Generated by Django 3.2.10 on 2022-07-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_building_cleanlinessevaluation_locationevaluation_noiseevaluation_safetyevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationevaluation',
            name='buildingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building'),
        ),
        migrations.AlterField(
            model_name='noiseevaluation',
            name='buildingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building'),
        ),
        migrations.AlterField(
            model_name='safetyevaluation',
            name='buildingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.building'),
        ),
    ]
