# Generated by Django 3.2.10 on 2022-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewtest_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bugScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='cleanAvg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='constructionScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='courierBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='deposit',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='externalNoiseScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='femaleOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='floorNoiseScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='internalNoiseScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='locationsAvg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='managementScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='moldScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='monthlyRent',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='noiseAvg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='parkingScore',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='safeAvg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='building',
            name='smellScore',
            field=models.FloatField(default=None),
        ),
    ]
