# Generated by Django 3.2 on 2022-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewtest_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtest',
            name='recommend',
            field=models.IntegerField(default=0),
        ),
    ]
