# Generated by Django 3.2.10 on 2022-07-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20220714_1836'),
        ('review', '0004_alter_reviewtest_recommend'),
    ]

    operations = [
    ]
