# Generated by Django 3.2.10 on 2022-07-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20220721_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='long',
            new_name='lng',
        ),
    ]
