# Generated by Django 3.2.10 on 2022-07-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_merge_20220716_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtest',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='bugScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='buildingId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.building'),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='constructionScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='courierBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='externalNoiseScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='femaleOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='floorNoiseScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='internalNoiseScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='managementScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='moldScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='monthlyRent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='parkingScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewtest',
            name='smellScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cleanlinessevaluation',
            name='buildingId',
            field=models.ForeignKey(db_column='buildingId', on_delete=django.db.models.deletion.CASCADE, to='review.building'),
        ),
        migrations.AlterField(
            model_name='reviewtest',
            name='recommend',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
