# Generated by Django 3.2.10 on 2022-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_rename_long_building_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='cleanAvg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='locationsAvg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='noiseAvg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='safeAvg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
